wandb: benchmark
stage_name: stage1
name: dummy-mae-l16
vars:
  optim:
    kind: adamw
    lr: 1.5e-4
    betas: [ 0.9, 0.95 ]
    weight_decay: 0.05

datasets:
  train:
    kind: dummy_dataset
    size: 1281167
    x_shape: [ 3, 224, 224 ]
    num_classes: 1000

model:
  kind: mae
  encoder:
    kind: vit.vit
    patch_size: 16
    kwargs: ${select:large:${yaml:models/vit}}
    optim: ${vars.optim}
  decoder:
    kind: vit.mae_decoder
    kwargs: ${select:default:${yaml:models/mae_decoder}}
    optim: ${vars.optim}

trainer:
  kind: mae_trainer
  precision: float32
  max_updates: 600
  effective_batch_size: 768
  mask_generator:
    kind: random_mask_generator
    mask_ratio: 0.75
  loss_function:
    kind: mae_loss
    normalize_pixels: true
    loss_fn:
      kind: mse_loss
  log_every_n_epochs: 1
  add_default_callbacks: false
  add_trainer_callbacks: false
  callbacks:
    - kind: train_time_callback
      every_n_updates: 50
    - kind: progress_callback
      every_n_updates: 50
