wandb: benchmark
stage_name: stage1
name: dummy-vit-b16
vars:
  optim:
    kind: adamw
    lr: 1.5e-4
    betas: [ 0.9, 0.95 ]
    weight_decay: 0.05

datasets:
  train:
    kind: dummy_dataset
    size: 1281167
    x_shape: [ 3, 224, 224 ]
    num_classes: 1000

model:
  kind: vit.vit
  patch_size: 16
  kwargs: ${select:base:${yaml:models/vit}}
  optim: ${vars.optim}
  mode: classifier
  pooling:
    kind: class_token

trainer:
  kind: classification_trainer
  precision: bfloat16
  backup_precision: float16
  max_updates: 600
  effective_batch_size: 2048
  log_every_n_epochs: 1
  add_default_callbacks: false
  add_trainer_callbacks: false
  callbacks:
    - kind: train_time_callback
      every_n_updates: 50
    - kind: progress_callback
      every_n_updates: 50
