wandb: benchmark
stage_name: stage1
name: dummy-mixer-b196
vars:
  optim:
    kind: adamw
    lr: 1.5e-4
    betas: [ 0.9, 0.95 ]
    weight_decay: 0.05

datasets:
  train:
    kind: dummy_dataset
    size: 1281167
    x_shape: [ 196, 128 ]
    num_classes: 1000

model:
  kind: benchmark.mixer
  depth: 12
  dim: 768
  optim: ${vars.optim}

trainer:
  kind: classification_trainer
  max_updates: 1000
  precision: bfloat16
  backup_precision: float16
  effective_batch_size: 16384
  log_every_n_epochs: 1
  add_default_callbacks: false
  add_trainer_callbacks: false
  callbacks:
    - kind: train_time_callback
      every_n_updates: 50
    - kind: progress_callback
      every_n_updates: 50
