vars:
  resolution: 224

kind: cifar100
split: train
sample_wrappers:
  - kind: x_transform_wrapper
    transform:
      - kind: kd_resize
        size: ${vars.resolution}
        interpolation: bicubic
      - kind: kd_imagenet_norm