vars:
  version: ???
  resize_resolution: 256
  crop_resolution: 224

kind: inat
version: ${vars.version}
split: train
sample_wrappers:
  - kind: x_transform_wrapper
    transform:
      - kind: kd_resize
        size: ${vars.resize_resolution}
        interpolation: bicubic
      - kind: center_crop
        size: ${vars.crop_resolution}
      - kind: kd_image_net_norm
  - kind: label_smoothing_wrapper
    smoothing: 0.1
collators:
  - kind: kd_mix_collator
    mixup_p: 1.0
    cutmix_p: 0.0
    apply_mode: batch
    lamb_mode: batch
    shuffle_mode: flip